name: "track"

on:
  schedule:
    - cron: '0 7 * * *'
  # Support manual trigger
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: ./scripts/requirements.txt
      - name: Install dependencies
        run: |
          echo 'Cache hit: ${{ steps.setup-python.outputs.cache-hit }}'
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt
      - name: Check Update
        id: check-update
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: python ./scripts/check-update.py
      - name: Download WeChat Linux Packages
        if: steps.check-update.outputs.released != 'none'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 5
          command: |
            mkdir -p downloads
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.deb &
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.rpm &
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.AppImage &
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_arm64.deb &
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_arm64.rpm &
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_arm64.AppImage &
            wget -q -P downloads https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_LoongArch.deb &
            wait
      - name: Do Update
        id: do-update
        if: steps.check-update.outputs.released != 'none'
        run: python ./scripts/do-update.py --released ${{ steps.check-update.outputs.released }} --url ${{ steps.check-update.outputs.url }}
      - name: Commit Changes
        if: steps.check-update.outputs.released != 'none'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add versions.json
          git commit -m "Detected WeChat update: ${{ steps.do-update.outputs.version }}"
          git push origin main
          echo "Successfully pushed changes (WeChat updated to ${{ steps.do-update.outputs.version }})"
      - name: Create Release
        if: steps.check-update.outputs.released != 'none'
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./release-notes.md
          name: ${{ steps.do-update.outputs.version }}
          tag_name: ${{ steps.do-update.outputs.version }}
          files: |
            downloads/*
